// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxeA4rSoYcLr_hOUSWOHKQd_ab09SdHoE',
    appId: '1:901479828045:web:f594dc94d8b2c4e1ec2a04',
    messagingSenderId: '901479828045',
    projectId: 'nafsia-cb81e',
    authDomain: 'nafsia-cb81e.firebaseapp.com',
    storageBucket: 'nafsia-cb81e.firebasestorage.app',
    measurementId: 'G-7KH9Z6YTEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4DJtANV4ONP7pRupYalk6QsQICDe8gb0',
    appId: '1:901479828045:android:a12cc26bebe6834cec2a04',
    messagingSenderId: '901479828045',
    projectId: 'nafsia-cb81e',
    storageBucket: 'nafsia-cb81e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTqC4QRYk1tSGvLKMyXvhqgukAwrA7Djg',
    appId: '1:901479828045:ios:78ba9120d6376582ec2a04',
    messagingSenderId: '901479828045',
    projectId: 'nafsia-cb81e',
    storageBucket: 'nafsia-cb81e.firebasestorage.app',
    iosBundleId: 'com.example.nafsia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTqC4QRYk1tSGvLKMyXvhqgukAwrA7Djg',
    appId: '1:901479828045:ios:78ba9120d6376582ec2a04',
    messagingSenderId: '901479828045',
    projectId: 'nafsia-cb81e',
    storageBucket: 'nafsia-cb81e.firebasestorage.app',
    iosBundleId: 'com.example.nafsia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxeA4rSoYcLr_hOUSWOHKQd_ab09SdHoE',
    appId: '1:901479828045:web:adf462fcb19ec8a5ec2a04',
    messagingSenderId: '901479828045',
    projectId: 'nafsia-cb81e',
    authDomain: 'nafsia-cb81e.firebaseapp.com',
    storageBucket: 'nafsia-cb81e.firebasestorage.app',
    measurementId: 'G-J4T7SB38SN',
  );
}
